#include QMK_KEYBOARD_H


#ifdef COMBO_ENABLE
#include HD_combo_def // this has the combo definitions
#endif

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(
                 KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P,
                 RCTL_T(KC_A), RALT_T(KC_S), RGUI_T(KC_D), RSFT_T(KC_F), LT(L_NUMPAD,KC_G), LT(L_FN_NUM,KC_H), RSFT_T(KC_J), RGUI_T(KC_K), RALT_T(KC_L), RCTL_T(KC_SCLN),
                 KC_Z, KC_X, KC_C, KC_V, KC_B, TT(5), LT(7,KC_MPLY), KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH,
                 KC_LEFT, KC_RGHT, KC_APP, LT(L_MEDIA_KBD,KC_MUTE), LT(L_FN_NUM,KC_BSPC), LT(L_NAV,KC_DEL), LT(L_MEDIA_KBD,KC_MUTE), LT(L_PUNCT,KC_SPC), LT(L_NAV,KC_ENT), LT(L_MEDIA_KBD,KC_MPLY), KC_UP, KC_DOWN),
	[1] = LAYOUT(
                 HD_LT4, HD_LT3, HD_LT2, HD_LT1, HD_LT0, HD_RT0, HD_RT1, HD_RT2, HD_RT3, HD_RT4,
                 HD_LM4, HD_LM3, HD_LM2, HD_LM1, HD_LM0, HD_RM0, HD_RM1, HD_RM2, HD_RM3, HD_RM4,
                 HD_LB4, HD_LB3, HD_LB2, HD_LB1, HD_LB0, KC_TRNS, KC_TRNS, HD_RB0, HD_RB1, HD_RB2, HD_RB3, HD_RB4,
                 KC_TRNS, KC_TRNS, LT(L_MEDIA_KBD,KC_MUTE), HD_LH2, HD_LH1, KC_TRNS, KC_TRNS, HD_RH1, HD_RH2, LT(L_MEDIA_KBD,KC_MPLY), KC_TRNS, KC_TRNS),
	[2] = LAYOUT(
                 KC_Z, KC_Q, RALT(KC_5), LALT(KC_7), LSA(KC_7), LALT(KC_4), KC_DLR, A(S(KC_2)), RALT(KC_3), LALT(KC_Y),
                 KC_LT, KC_LBRC, KC_LPRN, KC_LCBR, RSA(KC_5), RALT(KC_1), RSFT_T(KC_PAST), RGUI_T(KC_PEQL), RALT_T(KC_PPLS), RCTL_T(KC_PSLS),
                 KC_GT, KC_RBRC, KC_RPRN, KC_RCBR, LALT(KC_8), KC_TRNS, KC_TRNS, KC_UNDS, KC_PIPE, KC_AMPR, KC_CIRC, KC_PERC,
                 KC_TRNS, KC_TRNS, KC_TRNS, SK_DELWDL, SK_DELWDR, KC_TRNS, LSA(KC_8), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[3] = LAYOUT(KC_F9, KC_F10, KC_F11, KC_F12, KC_F13, KC_GRV, KC_6, KC_7, KC_8, KC_BSLS, LCTL_T(KC_F5), LALT_T(KC_F6), LGUI_T(KC_F7), LSFT_T(KC_F8), KC_F14, KC_SCLN, RSFT_T(KC_1), RGUI_T(KC_5), RALT_T(KC_9), RCTL_T(KC_SLSH), KC_F1, KC_F2, KC_F3, KC_F4, KC_F15, KC_PAUS, KC_TAB, KC_MINS, KC_2, KC_3, KC_4, KC_EQL, KC_PSCR, KC_LSCR, KC_TRNS, KC_BSPC, KC_ENT, KC_TRNS, KC_DEL, KC_0, KC_DOT, KC_COMM, KC_TRNS, KC_TRNS),
	[4] = LAYOUT(KC_LNUM, KC_HOME, KC_UP, KC_END, KC_PGUP, KC_PSLS, KC_P7, KC_P8, KC_P9, KC_PMNS, LALT_T(KC_TAB), KC_LEFT, KC_DOWN, KC_RGHT, KC_PGDN, KC_PAST, KC_P4, KC_P5, KC_P6, KC_PPLS, SK_UNDO, SK_CUT, SK_COPY, SK_PSTE, KC_SPC, TG(5), KC_TRNS, KC_PCMM, KC_P1, KC_P2, KC_P3, KC_PEQL, KC_TRNS, KC_TRNS, KC_TRNS, LGUI_T(KC_BSPC), LSFT_T(KC_ENT), KC_TRNS, KC_DEL, KC_P0, KC_PDOT, KC_C, KC_TRNS, KC_TRNS),
	[5] = LAYOUT(SK_QUIT, SK_CLOZ, SK_SCAP, SK_SCLP, SK_FAGN, SK_DOCBEG, KC_HOME, KC_UP, KC_PGUP, SK_PARAPRV, KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, SK_FIND, SK_WORDPRV, KC_LEFT, KC_DOWN, KC_RGHT, SK_WORDNXT, SK_UNDO, SK_CUT, SK_COPY, SK_PSTE, SK_PSTM, KC_ESC, KC_TAB, SK_DOCEND, KC_END, KC_DOWN, KC_PGDN, SK_PARANXT, SK_HISTPRV, SK_HISTNXT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, SK_HISTPRV, SK_HISTNXT, SK_ZOOMRST, SK_ZOOMOUT, SK_ZOOMIN),
	[6] = LAYOUT(
                 KC_NO, EE_CLR, AG_SWAP, CG_SWAP, LCA(KC_DEL), SK_KILL, KC_NUM, KC_EJCT, KC_NO, SK_ZOOMRST,
                 HD_AdaptKeyToggle, HD_L_QWERTY, HD_L_ALPHA, KC_VOLU, KC_BRIU, KC_NO, KC_MPRV, KC_MUTE, KC_MNXT, SK_ZOOMOUT,
                 QK_BOOT, AG_NORM, CG_NORM, KC_VOLD, KC_BRID, KC_NO, KC_NO, KC_NO, KC_MRWD, KC_MPLY, KC_MFFD, SK_ZOOMIN,
                 KC_NO, KC_NO, TG(L_NUMPAD), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};

