#include QMK_KEYBOARD_H

#ifdef COMBO_ENABLE
#include HD_combo_def // this has the combo definitions
#endif

#define ____ KC_TRNS
#define _no_ KC_NO

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
[L_QWERTY] = LAYOUT_grid(
    KC_Q, KC_W, KC_E, KC_R, KC_T, LT(L_MEDIA_KBD,KC_MUTE), LT(L_MEDIA_KBD,KC_MPLY), KC_PSLS, KC_P7, KC_P8, KC_P9, KC_PMNS, KC_Y, KC_U, KC_I, KC_O, KC_P,
    RCTL_T(KC_A), RALT_T(KC_S), RGUI_T(KC_D), RSFT_T(KC_F), LT(L_NUMPAD,KC_G),  KC_VOLD, KC_VOLU, KC_PAST, KC_P4, KC_P5, KC_P6, KC_PPLS, LT(L_FN_NUM,KC_H), RSFT_T(KC_J), RGUI_T(KC_K), RALT_T(KC_L), RCTL_T(KC_SCLN),
    KC_Z, KC_X, KC_C, KC_V, KC_B, KC_MRWD, KC_MFFD, KC_PCMM, KC_P1, KC_P2, KC_P3, KC_PEQL, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH,
    KC_LEFT, KC_RGHT, KC_APP, LT(L_FN_NUM,KC_BSPC), LT(L_NAV,KC_DEL), SK_HISTPRV, SK_HISTNXT, KC_C, KC_P0, KC_PDOT, KC_P0, KC_ESC, LT(L_PUNCT,KC_SPC), LT(L_NAV,KC_ENT), LT(L_FN_NUM,KC_TAB),  KC_UP, KC_DOWN),

[L_HDALPHA] = LAYOUT_grid(
    HD_LT4, HD_LT3, HD_LT2, HD_LT1, HD_LT0, LT(L_MEDIA_KBD,KC_MUTE), ____, ____, ____, ____, ____, LT(L_MEDIA_KBD,KC_MPLY), HD_RT0, HD_RT1, HD_RT2, HD_RT3, HD_RT4,
    HD_LM4, HD_LM3, HD_LM2, HD_LM1, HD_LM0, LT(L_NUMPAD,KC_TAB), ____, ____, ____, ____, ____, TT(L_NAV), HD_RM0, HD_RM1, HD_RM2, HD_RM3, HD_RM4,
    HD_LB4, HD_LB3, HD_LB2, HD_LB1, HD_LB0, ____, ____, ____, ____, ____, ____, ____, HD_RB0, HD_RB1, HD_RB2, HD_RB3, HD_RB4,
    ____, ____, ____, HD_LH2, HD_LH1, ____, ____, ____, ____, ____, ____, ____, HD_RH1, HD_RH2, ____, ____, ____),
    
[L_PUNCT] = LAYOUT_grid(
    KC_Z,   KC_Q,    RALT(KC_5), LALT(KC_7), LSA(KC_7), ____, ____, ____, ____, ____, ____, ____, LALT(KC_4), KC_DLR, A(S(KC_2)), RALT(KC_3), LALT_T(KC_Y),
    KC_LT,  KC_LBRC, KC_LPRN, KC_LCBR, RSA(KC_5), ____, ____, ____, ____, ____, ____, ____, RALT(KC_1), RSFT_T(KC_PAST), RGUI_T(KC_PEQL), RALT_T(KC_PPLS), RALT_T(KC_R),
    KC_GT,  KC_RBRC, KC_RPRN, KC_RCBR, LALT(KC_8), ____, ____, ____, ____, ____, ____, ____, KC_UNDS, KC_PIPE, KC_AMPR, KC_CIRC, KC_PERC,
    ____, ____, ____, SK_DELWDL, SK_DELWDR, ____, ____, ____, ____, ____, ____, ____, ____, LSA(KC_8), LSA(KC_9), LALT(KC_9), ____),

[L_FN_NUM] = LAYOUT_grid(
    KC_F9, KC_F10, KC_F11, KC_F12, KC_F13, KC_F16, ____, ____, ____, ____, ____, ____, KC_SLSH, KC_7, KC_8, KC_9, KC_MINS,
    LCTL_T(KC_F5), LALT_T(KC_F6), LGUI_T(KC_F7), LSFT_T(KC_F8), KC_F14, KC_F17, ____, ____, ____, ____, ____, ____, KC_ASTR, RSFT_T(KC_1), RGUI_T(KC_2), RALT_T(KC_3), RCTL_T(KC_PPLS),
    KC_F1, KC_F2, KC_F3, KC_F4, KC_F15, KC_F18, ____, ____, ____, ____, ____, KC_TAB, KC_MINS, KC_4, KC_5, KC_6, KC_EQL,
    KC_PSCR, KC_SCRL, ____, KC_BSPC, KC_ENT, ____, ____, KC_PAUS, ____, ____, ____, KC_INS, ____, KC_0, KC_DOT, KC_SCLN, KC_PENT),

[L_NUMPAD] = LAYOUT_grid(
    KC_NUM, KC_HOME, KC_UP, KC_END, KC_PGUP, ____, ____, ____, ____, ____, ____, ____, KC_PSLS, KC_P7, KC_P8, KC_P9, KC_PMNS,
    LALT_T(KC_TAB), KC_LEFT, KC_DOWN, KC_RGHT, KC_PGDN, ____, ____, ____, ____, ____, ____, KC_DLR, KC_PAST, KC_P4, KC_P5, KC_P6, KC_PPLS,
    SK_UNDO, SK_CUT, SK_COPY, SK_PSTE, KC_SPC, ____, ____, KC_INS, ____, ____, ____, KC_TAB, KC_PCMM, KC_P1, KC_P2, KC_P3, KC_PEQL,
    KC_F16, KC_F17, KC_F18, LGUI_T(KC_BSPC), LSFT_T(KC_ENT), KC_SCRL, KC_PAUS, KC_ESC, ____, ____, ____, KC_DEL, KC_C, KC_P0, KC_P0, KC_PDOT, KC_PENT),

[L_NAV] = LAYOUT_grid(
    SK_QUIT, SK_CLOZ, SK_SCAP, SK_SCLP, SK_FAGN, ____, ____, ____, KC_F7, KC_F8, KC_F9, ____, SK_DOCBEG, KC_HOME, KC_UP, KC_PGUP, SK_PARAPRV,
    KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, SK_FIND, ____, ____, ____, KC_F4, KC_F5, KC_F6, ____, SK_WORDPRV, KC_LEFT, KC_DOWN, KC_RGHT, SK_WORDNXT,
    SK_UNDO, SK_CUT, SK_COPY, SK_PSTE, SK_PSTM, ____, ____, ____, KC_F1, KC_F2, KC_F3, ____, SK_DOCEND, KC_END, KC_DOWN, KC_LALT, SK_PARANXT,
    SK_HISTPRV, SK_HISTNXT, ____, SK_DELWDL, SK_DELWDR, ____, ____, ____, KC_F10, KC_F11, KC_F12, ____, SK_HISTPRV, SK_HISTNXT, SK_ZOOMRST, SK_ZOOMOUT, SK_ZOOMIN),

[L_MEDIA_KBD] = LAYOUT_grid(
    QK_RBT, AG_SWAP, CG_SWAP, EE_CLR, LCA(KC_DEL), ____, KC_NUM, RGB_TOG, _no_, _no_, _no_, RGB_TOG, SK_KILL, KC_NUM, KC_EJCT, _no_, SK_ZOOMRST,
    HD_AdaptKeyToggle, HD_L_QWERTY, HD_L_ALPHA, KC_VOLU, KC_BRIU, KC_VOLD, KC_VOLU, RGB_MOD, RGB_VAI, RGB_SAI, RGB_HUI, _no_, _no_, KC_MPRV, KC_MUTE, KC_MNXT, SK_ZOOMOUT,
    QK_BOOT, AG_NORM, CG_NORM, KC_VOLD, KC_BRID, KC_BRID, KC_BRID, RGB_RMOD, RGB_VAD, RGB_SAD, RGB_HUD, CG_NORM, _no_, KC_MRWD, KC_MPLY, KC_MFFD, SK_ZOOMIN,
    _no_, _no_, _no_, AG_NORM, CG_NORM, KC_MPRV, KC_MNXT, KC_MPLY, _no_, _no_, _no_, _no_, KC_PAUS, KC_MPLY, KC_MSTP, KC_VOLU, KC_VOLD)
};

