OLED_ENABLE = no
#OLED_DRIVER = ssd1306
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = no
EXTRAKEY_ENABLE = yes
AUDIO_ENABLE = no
MUSIC_ENABLE = no

#DYNAMIC_MACRO_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
TRI_LAYER_ENABLE = yes

SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor

#HAPTIC FEEBACK
HAPTIC_ENABLE = no
SPLIT_HAPTIC_ENABLE = no

#PER KEY RGB
RGB_MATRIX_ENABLE = no
