#include QMK_KEYBOARD_H


#ifdef COMBO_ENABLE
#include HD_combo_def // this has the combo definitions
#endif

    
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(SK_COPY, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LNG2,
                 SK_PSTE, RCTL_T(KC_A), RALT_T(KC_S), RGUI_T(KC_D), RSFT_T(KC_F), LT(L_NUMPAD,KC_G), LT(L_FN_NUM,KC_H), RSFT_T(KC_J), RGUI_T(KC_K), RALT_T(KC_L), RCTL_T(KC_SCLN), KC_LNG1,
                 KC_AMPR, KC_Z, KC_X, KC_C, KC_V, KC_B, LT(7,KC_MUTE), LT(5,KC_ESC), LT(5,KC_ESC), LT(7,KC_MPLY), KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_EQL,
                 LT(6,KC_MUTE), KC_APP, LT(L_FN_NUM,KC_BSPC), LT(L_NAV,KC_DEL), LT(4,KC_LNG2), LT(4,KC_LNG1), LT(L_PUNCT,KC_SPC), LT(L_NAV,KC_ENT), LT(4,KC_TAB), LT(6,KC_MPLY)),
    [1] = LAYOUT(KC_TRNS, HD_LT4, HD_LT3, HD_LT2, HD_LT1, HD_LT0,   HD_RT0, HD_RT1, HD_RT2, HD_RT3, HD_RT4, KC_TRNS,
                 KC_TRNS, HD_LM4, HD_LM3, HD_LM2, HD_LM1, HD_LM0,   HD_RM0, HD_RM1, HD_RM2, HD_RM3, HD_RM4, KC_TRNS,
                 KC_TRNS, HD_LB4, HD_LB3, HD_LB2, HD_LB1, HD_LB0, LT(7,KC_MUTE), LT(5,KC_ESC), LT(5,KC_ESC), LT(7,KC_MPLY), HD_RB0, HD_RB1, HD_RB2, HD_RB3, HD_RB4, KC_TRNS,
                 KC_TRNS, KC_TRNS, HD_LH2, HD_LH1, LT(L_NAV,KC_SPC), LT(L_PUNCT,KC_LNG1), HD_RH1, HD_RH2, KC_TRNS, KC_TRNS),
    [2] = LAYOUT(KC_TRNS, KC_Z, KC_Q, RALT(KC_5), LALT(KC_7), LSA(KC_7), LALT(KC_4), KC_DLR, A(S(KC_2)), RALT(KC_3), LALT(KC_Y), KC_TRNS, KC_TRNS, KC_LT, KC_LBRC, KC_LPRN, KC_LCBR, LSA(KC_5), RALT(KC_1), LSFT_T(KC_PAST), LGUI_T(KC_PEQL), LALT_T(KC_PPLS), LCTL_T(KC_PSLS), KC_TRNS, KC_TRNS, KC_GT, KC_RBRC, KC_RPRN, KC_RCBR, LALT(KC_8), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_UNDS, KC_PIPE, KC_AMPR, KC_CIRC, KC_PERC, KC_TRNS, KC_VOLD, KC_VOLU, SK_DELWDL, SK_DELWDR, KC_TRNS, LALT(KC_9), KC_TRNS, LSA(KC_8), LSA(KC_9), KC_TRNS),
	[3] = LAYOUT(RGB_TOG, KC_F9, KC_F10, KC_F11, KC_F12, KC_F13, KC_SLSH, KC_7, KC_8, KC_9, KC_MINS, RGB_MOD, RGB_VAI, LCTL_T(KC_F5), LALT_T(KC_F6), LGUI_T(KC_F7), LSFT_T(KC_F8), KC_F14, KC_ASTR, RSFT_T(KC_1), RGUI_T(KC_2), RALT_T(KC_3), RCTL_T(KC_PPLS), RGB_HUI, RGB_VAD, KC_F1, KC_F2, KC_F3, KC_F4, KC_F15, QK_BOOT, KC_TRNS, KC_TRNS, KC_TRNS, KC_COMM, KC_4, KC_5, KC_6, KC_EQL, RGB_HUD, KC_TRNS, KC_TRNS, KC_TRNS, KC_SCLN, LT(L_MEDIA_KBD, KC_MUTE), KC_TRNS, KC_TRNS, KC_0, KC_DOT, SK_ZOOMRST),
	[4] = LAYOUT(RGB_TOG, TG(L_NUMPAD), KC_HOME, KC_UP, KC_END, KC_PGUP, KC_PSLS, KC_P7, KC_P8, KC_P9, KC_PMNS, RGB_MOD, RGB_VAI, LALT_T(KC_TAB), KC_LEFT, KC_DOWN, KC_RGHT, KC_PGDN, KC_PAST, KC_P4, KC_P5, KC_P6, KC_PPLS, RGB_HUI, RGB_VAD, SK_UNDO, SK_CUT, SK_COPY, SK_PSTE, KC_SPC, TG(5), KC_NO, KC_NO, LALT(KC_MINS), KC_PCMM, KC_P1, KC_P2, KC_P3, KC_PEQL, RGB_HUD, KC_TRNS, KC_TRNS, LGUI_T(KC_BSPC), LSFT_T(KC_ENT), KC_TRNS, KC_DEL, KC_P0, KC_PDOT, KC_C, SK_ZOOMRST),
	[5] = LAYOUT(KC_TRNS, SK_QUIT, SK_CLOZ, SK_SCAP, SK_SCLP, SK_PSTM, SK_DOCBEG, KC_HOME, KC_UP, KC_PGUP, SK_PARAPRV, KC_NUM, KC_VOLU, KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, SK_FIND, SK_WORDPRV, KC_LEFT, KC_DOWN, KC_RGHT, SK_WORDNXT, KC_TRNS, KC_VOLD, SK_UNDO, SK_CUT, SK_COPY, SK_PSTE, SK_FAGN, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, SK_DOCEND, KC_END, KC_DOWN, KC_PGDN, SK_PARANXT, KC_TRNS, KC_BRIU, KC_BRID, LT(L_MEDIA_KBD, KC_ESC), KC_APP, KC_TRNS, SK_ZOOMOUT, SK_HISTPRV, SK_HISTNXT, SK_ZOOMIN, SK_ZOOMRST),
	[6] = LAYOUT(RGB_TOG, QK_BOOT, EE_CLR, AG_SWAP, CG_SWAP, LCA(KC_DEL), SK_KILL, KC_NUM, KC_EJCT, KC_NO, SK_ZOOMRST, RGB_MOD, RGB_VAI, HD_AdaptKeyToggle, KC_NO, HD_L_QWERTY, HD_L_ALPHA, KC_BRIU, KC_VOLU, KC_MPRV, KC_MUTE, KC_MNXT, SK_ZOOMOUT, RGB_SAI, RGB_HUI, RGB_VAD, KC_NO, KC_NO, AG_NORM, CG_NORM, KC_BRID, QK_BOOT, KC_NO, KC_VOLD, KC_MRWD, KC_MPLY, KC_MFFD, SK_ZOOMIN, RGB_SAD, RGB_HUD, KC_NO, KC_NO, KC_PAUS, KC_MPLY, KC_NO, KC_NO, CG_NORM, AG_NORM, KC_NO, KC_NO)
};

